var bugs;
var gameBoundaries;
var cloudPlatforms;
var chickenPlayer;
var score = 0;
var activeAvatar = {egg: true, chicken: false, raptor: false, king: false, restart: false}
var lastCursor;
var scene;
var cake;
var coins; 
var eggSound; 
var gobble; 
var levelDown; 
var levelUp; 
var scream; 
var squish; 
var touchingObj;
var scoreText;
var cakeFire;
var devolve;
var music;
